//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrachInformation
    {
        public int BranchNo { get; set; }
        public string BranchName { get; set; }
        public string BranchCity { get; set; }
        public string BranchDistrict { get; set; }
        public string BranchManager { get; set; }
        public string BranchContact { get; set; }
    }
}
